//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tennis.Controls {
    
    public partial class EventControl {
        protected System.Web.UI.HtmlControls.HtmlGenericControl DialogCaption;
        protected System.Web.UI.WebControls.TextBox EventName;
        protected System.Web.UI.WebControls.DropDownList Classification;
        protected Bahns.Web.UI.WebControls.DatePicker BeginDate;
        protected Bahns.Web.UI.WebControls.DatePicker EndDate;
        protected System.Web.UI.WebControls.CheckBox League;
        protected System.Web.UI.WebControls.CheckBox Tournament;
        protected System.Web.UI.WebControls.CheckBox TeamPlay;
        protected System.Web.UI.WebControls.ValidationSummary vldSummary;
    }
}
