//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tennis.Controls {
    
    public partial class EventSummaryControl {
        protected System.Web.UI.WebControls.DropDownList EventTypeDrowDownList;
        protected System.Web.UI.WebControls.GridView GridView2;
    }
}
