//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tennis.Controls {
    
    public partial class MatchControl {
        protected System.Web.UI.HtmlControls.HtmlGenericControl DialogCaption;
        protected System.Web.UI.WebControls.DropDownList Event;
        protected System.Web.UI.WebControls.RequiredFieldValidator vldEvent;
        protected Bahns.Web.UI.WebControls.DatePicker Date;
        protected System.Web.UI.WebControls.TextBox Time;
        protected Sfg.Web.UI.Controls.AutoCompleteTextBox Winner1;
        protected System.Web.UI.WebControls.DropDownList Winner;
        protected System.Web.UI.WebControls.RequiredFieldValidator WinnerRequired;
        protected System.Web.UI.WebControls.DropDownList Loser;
        protected System.Web.UI.WebControls.RequiredFieldValidator LoserRequired;
        protected Tennis.Controls.SetScoreControl Set1;
        protected Tennis.Controls.SetScoreControl Set2;
        protected Tennis.Controls.SetScoreControl Set3;
        protected Tennis.Controls.SetScoreControl Set4;
        protected Tennis.Controls.SetScoreControl Set5;
        protected System.Web.UI.WebControls.CustomValidator ScoreValidator;
        protected System.Web.UI.WebControls.CheckBox Defaulted;
        protected System.Web.UI.WebControls.ValidationSummary vldSummary;
    }
}
