//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tennis.Controls {
    
    public partial class OpponentSummaryControl {
        protected System.Web.UI.WebControls.CheckBox CheckBox1;
        protected System.Web.UI.WebControls.CheckBox CheckBox2;
        protected System.Web.UI.WebControls.CheckBox CheckBox3;
        protected System.Web.UI.WebControls.CheckBox CheckBox4;
        protected System.Web.UI.WebControls.GridView GridView2;
    }
}
