//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tennis.Controls {
    
    public partial class PlayerControl {
        protected System.Web.UI.HtmlControls.HtmlGenericControl DialogCaption;
        protected System.Web.UI.WebControls.TextBox FirstName;
        protected System.Web.UI.WebControls.TextBox LastName;
        protected System.Web.UI.WebControls.ValidationSummary vldSummary;
    }
}
