//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tennis.Controls {
    
    public partial class SetScoreControl {
        protected System.Web.UI.HtmlControls.HtmlGenericControl setwrap;
        protected System.Web.UI.WebControls.Literal Set;
        protected System.Web.UI.WebControls.TextBox W;
        protected System.Web.UI.WebControls.TextBox L;
        protected System.Web.UI.HtmlControls.HtmlGenericControl tiebreak;
        protected System.Web.UI.WebControls.TextBox WT;
        protected System.Web.UI.WebControls.TextBox LT;
    }
}
