//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tennis {
    
    public partial class PlayerMatches {
        protected System.Web.UI.WebControls.DropDownList TimeSpan;
        protected System.Web.UI.WebControls.Label TimeSpanLabel;
        protected System.Web.UI.WebControls.Literal txtRecord;
        protected System.Web.UI.WebControls.GridView GridView1;
        protected System.Web.UI.WebControls.DataGrid dataGrid;
    }
}
