//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tennis {
    
    public partial class Master {
        protected System.Web.UI.HtmlControls.HtmlForm Form1;
        protected System.Web.UI.WebControls.HyperLink HomeImage;
        protected System.Web.UI.WebControls.HyperLink HomeTitle;
        protected System.Web.UI.WebControls.LoginStatus LoginStatus1;
        protected System.Web.UI.WebControls.Menu MainMenu;
        protected System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;
        public System.Web.UI.HtmlControls.HtmlTableRow EditingControls;
        public System.Web.UI.HtmlControls.HtmlGenericControl ButtonsPlaceHolder;
        protected System.Web.UI.WebControls.Button Submit;
        protected System.Web.UI.WebControls.Button Cancel;
        protected System.Web.UI.WebControls.Button Edit;
        protected System.Web.UI.WebControls.Literal Status;
    }
}
