//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tennis.Account {
    
    public partial class NewUser {
        protected System.Web.UI.WebControls.CreateUserWizard CreateUserWizard1;
        protected System.Web.UI.WebControls.CreateUserWizardStep CreateUserWizardStep1;
        protected System.Web.UI.WebControls.CompleteWizardStep CompleteWizardStep1;
    }
}
